In [31]:
### import 
import statsmodels
import numpy as np
import matplotlib.pylab as plt


In [32]:
### 1. create a matrix (numpy array) of ones sized (100 X 50) use .shape to check your matrix
one_mx = np.ones((100, 50))
one_mx.shape

(100, 50)

In [33]:
### 2. create a matrix of zeros the same size as the matrix from (1) use numpy
zero_mx = np.zeros((100,50))
zero_mx.shape

(100, 50)

In [34]:
### 3. create a new matrix that will be the concatenation of (1 & 2) --> matrix sized (200, 50)
zero_one_mx = np.concatenate((one_mx,zero_mx))
zero_one_mx

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [35]:
### 4. Add the two matrices (from 1 & 2) to get one matrix (100 X 50) --> check yourself (do all enteries show 1?)
add_mx = one_mx + zero_mx
add_mx.shape

(100, 50)

In [36]:
### 5. Use the function we have created few warm-ups ago to create two matrices 20X40 from multivariate normal distribution
n1 = np.random.normal(size=(20,40))
n2 = np.random.normal(size=(20,40))



In [49]:
### 6. let's try to make two operations: 
    # - matrix multiplication (first test it on a 2X2 matrices)
    # - element wise multiplication 
m = (n1 * n2)
# print(m)
print(m.shape)

np.multiply(n1, n2)

(20, 40)


array([[-7.80551608e-01, -5.73785627e-02,  4.10434377e-01,
        -5.35838537e-01,  3.59742253e+00, -1.43164443e+00,
        -1.06211763e+00,  6.42475097e-02, -1.33297934e-01,
        -2.12377340e-01,  1.19578447e-01,  3.87662739e-02,
         9.26941642e-02, -2.06215047e-01,  9.88497293e-01,
        -3.89859395e-01,  6.95017819e-01,  6.53941593e-01,
         5.89474182e-01, -2.15099244e-01, -8.92941170e-01,
        -3.11973503e-01,  5.51856284e-01, -4.12741436e-02,
        -3.17031416e-02, -1.00443173e+00, -2.18356603e-02,
        -2.19298756e-01,  5.06212196e-01,  2.27339850e-01,
        -1.32517381e+00,  2.81116886e-01,  2.10457265e-02,
        -1.48205905e-01, -7.04142916e-01, -3.90695771e-01,
        -5.13220659e-01, -1.58684776e+00,  1.53401811e-01,
        -4.57647716e-03],
       [-5.21601100e-01, -6.91724747e-02, -1.83518634e-02,
         7.65095092e-02,  5.66809464e-01,  1.54641203e-01,
        -6.16336009e-01,  8.06625952e-02, -2.27696441e-01,
         1.64667169e-01,  1.00

In [ ]:
### 7. let's create again the linear equations Y = XW + noise
##### Noise should come from univariate normal distribution with mean 0 and variance 0.1 



In [ ]:
### 8. Can you calculate the weight (coeficients) matrix? Do it.
### Write down the equation of the multiple regression model


In [ ]:
### 9. Create a function that calculates the mean squared error 


In [ ]:
### 10. Plot the errors to check for normality


In [ ]:
### 11. Plot scatter plots of the independent variables against the target value to check for violations of the constant variance assumption for errors 


In [ ]:
### 12. Calculate R squared (you can use statsmodels)


In [25]:
# 1. create a matrix (numpy array) of ones sized (100 X 50)


(100, 50)

In [26]:
# 2. create a matrix of zeros the same size as the matrix from (1)


(100, 50)

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

(100, 50)